### ISSUE TITLE
Ly - Tutorial on how to create a Jekyll blog

### ISSUE THREAD

**Issue by Ly900** [ga-dc/tutorials_for_past_you#10]
**Tutorial:** How to build a Jekyll blog
**Tutorial link:** http://ly900.github.io/blog/
**Feedback I'd Like:** I wasn't clear on the use of the master branch and gh-pages. I wasn't sure if I should continually update both or just gh-pages or just master and then merge. I did not get a clear understanding of the purpose of each. Also, I am not sure how to style it with SASS.

**Comment by andrewsunglaekim** [comment]
only have to update `gh-pages` if you want, but good practice to update `master` as well.

**Comment by andrewsunglaekim** [comment]
looks great though! :+1:
