### ISSUE TITLE
Bash Profile Tutorial

### ISSUE THREAD

**Issue by ArmaniH** [ga-dc/tutorials_for_past_you#11]
[Link to tutorial](https://gist.github.com/ArmaniH/4a8c1108afdca7a57f3d)

There were quite a bit of options and methods to update the bash_profile, so I selected a couple that I've found most useful and covered setting them up. I approached this with the assumption the user is at least somewhat familiar with using terminal.

I guess feedback wise, input on areas I maybe was too simple or vague and if my assumptions were warrented.

**Comment by jshawl** [comment]
:+1: Are swedes minimalists? and awesome post topic! I'd love to see you add this to a personal site or blog. 

I think your assumptions are good! - Doesn't feel too simple to me. I'd also recommend a "where to go next" section, like creating aliases or functions in your bash profile.

Oo also maybe a mention of dotfiles http://dotfiles.github.io/
