### ISSUE TITLE
Angular Filters Tutorial

### ISSUE THREAD

**Issue by brittonwalker** [ga-dc/tutorials_for_past_you#12]
A tutorial on Angular's built-in Filters.

https://brittonwalker.github.io/ 

I had a lot of fun doing this. It really solidified my learning of this particular subject and found it useful. I also really liked having to learn how to implement a jekyll blog using github pages. This might be a nice weekend assignment midway through the course. I would like any feedback as to whether or not this seemed clear and/or how you personally think it could be improved.

**Comment by andrewsunglaekim** [comment]
`It really solidified my learning of this particular subject and found it useful.` thats the secret sauce bro

**Comment by nolds9** [comment]
Major props for a Rick and Morty themed tutorial! Loved the way you crafted a narrative as well as broke the code down into logical steps that were clear in scope. I learned a ton going through this, and its clear you had fun with this assignment! 

Pro-tip: recommend using `single ticks` for inline code snippets. Also would suggest including a link to the solution code at the end.

Look forward to the posts to come!
