### ISSUE TITLE
Git-tips

### ISSUE THREAD

**Issue by schersh** [ga-dc/tutorials_for_past_you#15]
Completeness: 2.5 
I did not budget enough time for myself to complete this assignment, so my Git Tips tutorial is currently only available as a ReadMe file on GitHub: https://github.com/schersh/Git-tips
The tutorial is very bare bones right now, but I'd appreciate any feedback on specific topics it would be good to cover for a beginning developer, and maybe how to add in some practice scenarios.

**Comment by jshawl** [comment]
:+1: this is helpful! I'd like to see you write in a more prosaic style... explaining some of the assumed concepts, like "What does it mean to have a remote named upstream?"

Let me know if you'd like to pair on setting up a blog!
