### ISSUE TITLE
ToryBurgett

### ISSUE THREAD

**Issue by toryburgett** [ga-dc/tutorials_for_past_you#16]
https://gist.github.com/toryburgett/477b3034dab75821267e
Any input is greatly appreciated.

**Comment by amaseda** [comment]
This is great. Love the deep dive into promises -- actually learned a thing or two! The below suggestions are some next steps but this was a great read. Let me know if you end up writing more posts -- happy to take a look.
- Is there any other helpful information you could provide on `resolve` and `reject`? What do their return values look like? What's going on in that error event listener?
- Be consistent with indentation in examples. It's very important that they're readable in a tutorial context. You might also benefit by adding space between sections of your code so readers can clearly see the different components at play.

:+1: :+1: :+1:

**Comment by toryburgett** [comment]
@amaseda Thank you very much for your input! I am planning on tuning up this blog post this weekend, can I ask for your input again next week? Again, thank you Adrian.

**Comment by amaseda** [comment]
Of course, just let me know.
