### ISSUE TITLE
Chase's blog

### ISSUE THREAD

**Issue by cpgruber** [ga-dc/tutorials_for_past_you#17]
http://cpgruber.github.io/2016/01/02/deploying-a-mean-app.html

All comments welcome

**Comment by jshawl** [comment]
:+1: awesome post! 2 comments:

1) Images are helpful when describing UI's like Herokus.
2) You can keep a local env.js reference in the code like so:

``` js
var fs = require("fs");
var env = fs.existsSync("./env.js") ? require("./env") : process.env;

console.log(env.key);
```

This will prevent you from having to toggle that comment everytime you deploy.
