### ISSUE TITLE
ActionMailer

### ISSUE THREAD

**Issue by jacohen10** [ga-dc/tutorials_for_past_you#19]
Would have loved to make this node or angular related, but spent a lot of time on rails over break. Hoping to make a lot of progress with node this week.

On how I set up a mailer
http://jacohen10.github.io/actionmailer

Feedback: prefer asking a rails question at the moment, but any general feedback I guess.

**Comment by amaseda** [comment]
Great job with this. Super easy to understand - don't think anybody would have a problem setting ActionMailer up based on your  instructions. Some suggestions below.
- Start the post off with some framing. What is ActionMailer? Why would we use it?
- You could also start off with a preview of the tools being used (e.g., Figaro) and, if it makes sense, take care of any setup/installation at the start.
- Noticed you used method name `order_ahead_mailer`. I'm guessing this is from your Project 2. In the case of a tutorial, I would either (1) use a generic name that explains the purpose of the method or (2) add some text that talks about the example code you are using (e.g., "This is from a food ordering app I made.").
- Use proper indentation when it's required (e.g., those longer bits of code in Steps 1 and 2). Code readability is super important in tutorials.

Let me know if you end up writing any other posts -- happy to take a look!

:+1: :+1: :+1:
