### ISSUE TITLE
Eric Stennett - Using the Revealing Module Pattern in an Angular Service

### ISSUE THREAD

**Issue by estennett** [ga-dc/tutorials_for_past_you#21]
http://estennett.github.io/angular_tutorial/

I used an automated page in GitHub for easy use of Markdown, however I'll probably transition over to a custom page later.

It felt good to write this blog post, I felt it helped me solidify many of the basic Angular concepts.  I'll be looking to write future blog posts for sure.

General feedback is appreciated.

**Comment by andrewsunglaekim** [comment]
`It felt good to write this blog post, I felt it helped me solidify many of the basic Angular concepts` now you know the secret

**Comment by nolds9** [comment]
:thumbsup: Awesome blog! Really liked the walkthrough, step-by-step examples, and narrative of this tutorial.  I learned a ton, and will go practice my RMP with Ajax & Angular!

Pro-tip: use`inline comments` for code snippets/examples in text.  Also love GH Pages, but would recommend looking into [Ghost's]("http://github.com/TryGhost/Ghost") platform.
