### ISSUE TITLE
M. Shofner - Winter HW

### ISSUE THREAD

**Issue by MarkhamShofner** [ga-dc/tutorials_for_past_you#23]
Comfort: 4.5
Completeness: 4.5

I need to either work through Ghost or Jekyll, to make a public facing blog that supports markdown. I currently have Ghost running on my own computer's server, but it doesn't play well with Heroku, so I'm looking for a workaround here.

My post (link below) covers problem solving, using a project euler question as a lens for exploration. 

https://markhamshofner.wordpress.com/

**Comment by mattscilipoti** [comment]
:+1:  I'd like to do more exercises like this at GA.

For Heroku, looks like you may just need a Profile: https://www.howtoinstallghost.com/how-to-install-ghost-on-heroku/
Or, you could use the "easy" button (if it works): https://github.com/cobyism/ghost-on-heroku
