### ISSUE TITLE
Rebecca tutorial: React

### ISSUE THREAD

**Issue by rebeccaestes** [ga-dc/tutorials_for_past_you#24]
I went through a React course on Udemy over the break, so <a href="https://gist.github.com/rebeccaestes/af41586a2bc99c6696db">my tutorial</a> walks you through building a (very) simple app. I was at 250 lines by the time I finally finished properties, so states ended up being a little rushed ... as you will see by the example state I built.

**Comment by ebirving** [comment]
Awesome, Rebecca! React can be pretty dizzying, and you really made it feel accessible :smile: 

Hopefully your next step is to build a blog!
