### ISSUE TITLE
Deployment Tutorial

### ISSUE THREAD

**Issue by ghost** [ga-dc/tutorials_for_past_you#27]
Posted on http://householderonline.com/2016/01/04/deploying-to-heroku-a-short-tutorial/ and r/programming.

I'm not quite clear on how to include seed data in case the database connection doesn't work.  Had no issues with this when deploying my Rails app; a different story when deploying Mongo.

Working also on a many-to-many Rails app tutorial and would like feedback on that when I complete it.

**Comment by ghost** [comment]
r/programming link:  https://www.reddit.com/r/programming/comments/3zdm66/a_quick_tutorial_for_heroku_deployment/

**Comment by jshawl** [comment]
:+1: Nice tutorial! I recommend adding some styling for your code blocks so they show up as a monospace font and not italic. 

I also recommend either including a link to your repo so other people can follow along, or mention something about sqlite not working on heroku and how to convert to postgres
