### ISSUE TITLE
Matt Popovich -- How to Build and Deploy a Simple Twitter Bot Super Fast with Node.js and Heroku

### ISSUE THREAD

**Issue by mpopv** [ga-dc/tutorials_for_past_you#28]
Blog post:
https://medium.com/@mattpopovich/how-to-build-and-deploy-a-simple-twitter-bot-super-fast-with-node-js-and-heroku-7b322dbb5dd3#.bdb3n4x6c

App I built in the process of figuring out the best way to teach this:
https://github.com/mpopv/Star-Wars-Titlebot
https://twitter.com/SWTitlebot

This is really a Tutorial for Past Me in the most literal sense because it's exactly what I wish I could have found somewhere else weeks ago--a guide that cuts straight to getting off the ground with the Twitter API as quickly as possible. Other guides I found tended to get the reader bogged down with unnecessary dependencies and extraneous external APIs because they were more of the author charting the journey of a particular bot that they built, rather than showing someone else how to build a barebones bot.

I chose Medium because building the bot and writing this ended up taking quite a bit longer than I expected, but I do want to port it to a handrolled personal blog sometime in the near future.

**Comment by andrewsunglaekim** [comment]
hell yeah! Now you have a guide for it when you need it!

**Comment by mattscilipoti** [comment]
:tada: This is impressive.  I enjoyed reading the post, looking through the code, and drifting through the tweets.
