### ISSUE TITLE
Alice Frumin Tutorial

### ISSUE THREAD

**Issue by alifrumin** [ga-dc/tutorials_for_past_you#29]
http://alifrumin.github.io/JKblog/2016/01/04/mail-merge.html

comfort: 3/5
completeness: 3/5

I put together two jekyll blogs one using a template and one without and deployed them both to github pages. I learned a fair amount about that gh-pages and jekyll... a little about ruby  and also about markdown. I struggled to come up with a good blog topic so I started two one on a MEAN stack app and one on mail merges, this is a link to the mail merge one (the MEAN stack one is also on the same jekyll site). It still needs work but I want to explore it a little more and build out the comparisons and include some code snippets.

**Comment by ebirving** [comment]
Promising starts to both! I would be cool if you could think of a custom implementation of a mail-merge-type thing -- and write up a walkthrough to finish off that post...
