### ISSUE TITLE
blog joe-gz

### ISSUE THREAD

**Issue by joe-gz** [ga-dc/tutorials_for_past_you#3]
https://joegz.wordpress.com/2015/12/28/combining-two-json-files-in-angular/

feedback I'd like:
Is this a reasonable topic?
Is it too long?
What else can I add to it to make it a better blog?

most importantly: Do you have any thoughts on how I can clean up the code?

**Comment by ebirving** [comment]
1. Yes!
2. Nope.
3. Formatting in the code snippets: https://codex.wordpress.org/Writing_Code_in_Your_Posts
4. Maybe look into using ES 2015's `let`-scoped variables in for loops as an alternate solution to your looping problem?
