### ISSUE TITLE
Switching From A Mac OSX Web Development Setup to A Linux Based Setup

### ISSUE THREAD

**Issue by KoryJCampbell** [ga-dc/tutorials_for_past_you#34]
https://medium.com/@koryjcampbell/switching-from-mac-osx-to-linux-based-elementaryos-309df114f648#.v6fl4agws

**Comment by amaseda** [comment]
Great post. I've never set up a Linux machine so learned a lot from this. Some suggestions...
- Blog posts (and lesson plans!) can always benefit from some framing. Wouldn't hurt to talk about why you're making the switch (beyond getting a new machine) and what might be more appealing about a Linux setup vs. Mac.
- Go into what exactly `ElementaryOS` is. Why did you pick it vs. other options? What are some other popular / recommended options?
- For readers who are not well-versed in Linux, it might be helpful for you to explain what commands like `apt-get` mean.

:+1:
