### ISSUE TITLE
JMoon: tutorial on web scraping/JSONification with Node.js

### ISSUE THREAD

**Issue by mooniker** [ga-dc/tutorials_for_past_you#6]
Tutorial on web scraping legal summaries with Node.js:

gist: https://gist.github.com/mooniker/d5852ff5abb6f62e8967
code on github: https://github.com/mooniker/va_court_opinion_jsonifier

My commits match the flow of the tutorial, so I may add links or something later.

I was trying to target the material to journalists or people who don't necessarily have a strong background in coding, so I tried not to assume the reader knew anything other than the listed prereqs. That added considerably to the length of the piece, which I'm a bit worried about, and, I dunno, maybe it's awkward to assume the reader knows jQuery and JSON but doesn't know basic JavaScript commands.

I'm constantly wondering whether I left something out or by adding too much detail, I'm making it more confusing or leaving out or obscuring something that's actually important.

**Comment by andrewsunglaekim** [comment]
I think it's fine to make assumptions and list them like you did. Sets the stage up for understanding and clarity. That said I would include `express` as a requirement than you can leave out some of the clarifications on express.  

I really do like how explicit you are, but in some cases comments in your code snippets are plenty. (eg. no need to explain `$`, `text()`, and `eg()`)

Often times i'll do what you are doing by providing code comments, and then anything I think is fundamental to the understanding:

> ill plug in a note using `>`

Really great post though! Look forward to reading more from you =D
