### ISSUE TITLE
ThomasS tutorial

### ISSUE THREAD

**Issue by solowt** [ga-dc/tutorials_for_past_you#8]
gh-pages: http://solowt.github.io/2016/01/03/wmata-angular.html
medium: https://medium.com/@thomassolow/building-a-front-end-only-app-with-angular-e67d1d7573d0#.dhq61esu3

I used medium, but I plan on transferring this to github pages at some point.

any feedback would be helpful.

edit- added jekyll blog link.  still have to add the code blocks, should get to that tomorrow morning.

**Comment by nolds9** [comment]
:+1:  Great article, and clear tutorial.  Really liked the example you picked, and the approach you took to breaking down the app, and the steps you took to solve your problem.  Each component was well explained, and I especially liked that you switched to Jekyll to be easier to view(grab) code snippets! Would also recommend Ghost as another option.

Some minor things to keep in mind for the posts to come.  Would add a bit more on the transition between each file/component, and greater commentary on how they work together.  Also, I think a personal narrative or framing in the beginning as to why you choose this API/ problem to solve.  

Definitely learned a bunch. Thanks!
