### ISSUE TITLE
Tyler Crosse - Tutorial

### ISSUE THREAD

**Issue by tylercrosse** [ga-dc/tutorials_for_past_you#9]
I just reread the prompt and realized I totally missed the 'step-by-step guide that goes from Point A to some Point B' part. Ooops! I'll write another post, but here's what I have at the moment just in case.

[ES6 Arrows on Github Gist](https://gist.github.com/tylercrosse/b4f3ac5edec4b2741850)

I was really trying to focus on keeping this post concise and understandable. I would love feedback, particularly on any part of it that doesn't make sense, could be cut down or expanded on.

**Comment by amaseda** [comment]
Great post. Learned a lot from it. Also realized you explained the question I just asked you in IRL in the lesson plan! 

Only suggestion I have is to be more consistent with the examples you use in the `Arrows - shorter functions` section. That's only a small thing though - overall the post is just the right length and none of the content is superfluous.

Let me know if you end up writing another post - happy to take a look.
